# Generated by Django 6.0.6 on 2026-06-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
